---
title: Resumen de Métodos de Imputación Normalizado
output: html_document
---

```{r}
# Instalar y cargar el paquete dplyr si aún no está instalado
if (!require(dplyr)) {
  install.packages("dplyr")
}
library(dplyr)

# Crear un dataframe con los datos
imputacion <- c("Imputación de la media", "Imputación por vecino más cercano", "Imputación por Media",
                "Imputación por mediana", "Hot-deck aleatorio", "Hot-deck secuencial", "Cold_deck",
                "Hot-deck aleatorio", "Hot-deck secuencial", "Cold Deck", "Imputación por vecino más cercano",
                "Imputación por Media", "Imputación por tasas", "Imputación por vecino más cercano",
                "Cold_deck;Hot-deck jerárquico;", "Hot-deck aleatorio", "Hot-deck secuencial", "Imputación por tasas",
                "Imputación por vecino más cercano; Hot-deck secuencial", "Imputación por tasas", "Imputación de la media",
                "Imputación de razón", "Imputación por vecino más cercano", "Imputación fraccionada", "Hot-deck secuencial",
                "Imputación por vecino más cercano", "Imputación por Media", "Imputación por mediana",
                "Hot-deck aleatorio", "Imputación por mediana", "Imputación por modelos Lasso logit Lasso", "Imputación por medianas condicionadas")

# Crear un dataframe
df_imputacion <- data.frame(Imputacion = imputacion)

# Crear un resumen de conteo de métodos de imputación
resumen_imputacion <- df_imputacion %>%
  group_by(Imputacion) %>%
  summarise(Count = n())

# Normalizar los datos
resumen_imputacion <- resumen_imputacion %>%
  mutate(Normalized = (Count / sum(Count)) * 100)

# Imprimir la tabla de resumen normalizada
knitr::kable(resumen_imputacion, caption = "Resumen de Métodos de Imputación Normalizado")
